### ISSUE TITLE
deep linking to latest version with frames

### ISSUE THREAD

**Issue by maxcellent** [maxcellent/javadoc.io#1]
From: Paul

Hi, are you still maintaining javadoc.io and is there some place where we can submit issues? (I didn't find a Github repo.)  Basically I would like to request a way to link to the latest version of a class with frames.  It seems that currently we have to choose between using "latest" without frames or specifying a version to get frames.

**Comment by maxcellent** [comment]
Have you tried this: 

For latest version just put latest in your url javadoc.io/page/{org}/{artifact}/latest/{page}
For example: javadoc.io/page/org.mockito/mockito-all/latest/org/mockito/stubbing/Answer.html

Feel free to re-open if you still have this issue.

**Comment by pushbit** [comment]
That works well for displaying the latest version of the page, but it doesn't include the package and class list frames.  To get those it seems we have to use a URL like below, which must include the specific version.

https://static.javadoc.io/org.mockito/mockito-all/2.0.2-beta/index.html?org/mockito/stubbing/Answer.html

If there isn't currently a way to get the latest version with frames, can we re-open this issue?

**Comment by maxcellent** [comment]
@pushbit with the latest UI it should be a lot easier to create a deep link to the latest version. Feel free to re-open if you still see the issue.
