### ISSUE TITLE
Scanning not running?

### ISSUE THREAD

**Issue by brettwooldridge** [maxcellent/javadoc.io#10]
It seems the scanner is either not running, or is running (possibly) weeks behind.  I have several projects that appear to be out of sync:

* [SansOrm](https://github.com/brettwooldridge/SansOrm)
* [Influx4j](https://github.com/brettwooldridge/influx4j)

**Comment by srbala** [comment]
Same PF4J packages https://github.com/pf4j/pf4j, system still points to `2.1.0`

https://search.maven.org/#artifactdetails%7Corg.pf4j%7Cpf4j%7C2.2.0%7Cjar
https://search.maven.org/remotecontent?filepath=org/pf4j/pf4j/2.2.0/pf4j-2.2.0-javadoc.jar

**Comment by maxcellent** [comment]
@brettwooldridge , @srbala 

we have fixed an issue not able to index jars. Verified both both of them are fixed now.
