### ISSUE TITLE
open sourced javadoc.io

### ISSUE THREAD

**Issue by typekpb** [maxcellent/javadoc.io#11]
First of all: thanks for the product that just works.

I'd love to see javadoc.io open sourced.

My motivation is:
* running on premises (in the internal infrastructure)
 
With following features:
* ability to proxy private maven repositories
* ability to proxy not only *-javadoc.jar files but also jar files with configurable classifiers (as versioning the  generated documentation sounds like the right way to go for me)

any chance to see that happening ever or in near future :) ?

**Comment by robeden** [comment]
I don't need the second feature, but would also be interested in an on-prem solution for internal repos.

**Comment by KengoTODA** [comment]
Not sure it helps you or not, but here is a clone of javadoc.io: https://github.com/KengoTODA/javadocky 
so you can fork it and deploy onto your on-premise.

**Comment by typekpb** [comment]
Excelent, thanks for the reference
