### ISSUE TITLE
521 - web server is down

### ISSUE THREAD

**Issue by ben-manes** [maxcellent/javadoc.io#115]
<img width="1792" alt="Screen Shot 2023-02-02 at 1 00 23 AM" src="https://user-images.githubusercontent.com/378614/216278373-fb04a520-f9f3-4bd1-be27-9aacba09e7c1.png">

**Comment by maxcellent** [comment]
service is back to normal, will investigate root causes

**Comment by trustin** [comment]
Thanks a lot for taking care of the service. 🙇
