### ISSUE TITLE
Sync up issues with Maven central?

### ISSUE THREAD

**Issue by gt-tech** [maxcellent/javadoc.io#12]
Not sure if this is right place to report an issue, it is my understanding that javadoc.io automatically syncs up with Maven central. I have a opensource component available in Maven central whose first version was automatically synced up with javadoc.io but a few week ago i released the second version (2.0.0) however I do not see this new version's document in javadoc.io

<dependency>
    <groupId>org.bitbucket.gt_tech</groupId>
    <artifactId>nano-rxnetty-mvc-server</artifactId>
    <version>2.0.0</version>
</dependency>

Not sure if I am missing a step in pushing new version doc to appear on javadoc.io.

**Comment by gt-tech** [comment]
Figured, I had to access the 2.0.0 version from browser to trigger the site to load newer version. I am not sure if its the right process for pulling in new version but it does the trick for me.

**Comment by maxcellent** [comment]
FYI the scheduled job is also fixed to be able to pick up the new version. You shouldn't have to manually sync doc anymore. Please reopen this ticket if this happens again.
