### ISSUE TITLE
Use access as update trigger

### ISSUE THREAD

**Issue by brettwooldridge** [maxcellent/javadoc.io#13]
Given the use of a CDN, I'm not sure if this is possible, but it would be useful/interesting if access to a JavaDoc URL could act as a trigger to prioritize a check for new version for refresh.

For example, access to ``http://javadoc.io/doc/org.springframework/spring-core`` clearly expresses interest, by *someone*, in the JavaDoc for spring-core.  Therefore, a prioritized refresh check could be scheduled for that project.

The benefit is, there are likely tens of thousands of projects whose JavaDoc is never accessed on javadoc.io, so leveraging evidence of interest (as expressed via explicit access) could allow javadoc.io to be more efficient in refreshing.

The side-benefit is that frequently accessed projects would be more likely to be up-to-date JavaDoc on the site.

**Comment by maxcellent** [comment]
This is doable but also not easy. With the latest build the server should be able to pick up any new versions in 24 hours. 

Feel free to reopen if there are more concerns to refresh even more frequently.

**Comment by brettwooldridge** [comment]
Thanks!
