### ISSUE TITLE
Issue With Eureka Client @EnableEurekaClient

### ISSUE THREAD

**Issue by Akashnkumar1** [maxcellent/javadoc.io#141]
@EnableEurekaClient But didn't worked in microservice architecture

![image](https://user-images.githubusercontent.com/29744510/233777041-f87be004-b3ab-4180-984e-718e6d9f2cfe.png)

**Comment by maxcellent** [comment]
this issue tracker is for javadoc.io, which is hosting javadoc library. For the particular issue, please raise to relevant lib issue tracker.
