### ISSUE TITLE
Linking to 'latest' docs with frame On results in a XML error

### ISSUE THREAD

**Issue by noloader** [maxcellent/javadoc.io#165]
Hi Everyone,

I'm trying to link to the latest docs for ESAPI's Validator class. The version specific URL is https://www.javadoc.io/static/org.owasp.esapi/esapi/2.5.2.0/index.html?org/owasp/esapi/Validator.html.

When I change '2.5.2' to 'latest', it results in a XML error with frames On.

![javadocs-io-error](https://github.com/maxcellent/javadoc.io/assets/3538226/447db954-ef39-4abf-a5af-8e07aed256ee)

Others encounter the problem, too. See https://groups.google.com/a/owasp.org/g/esapi-project-users/c/I_k_aPcG_Fw/m/NCjVO_U9AwAJ .

It would be very useful if we could always link to the latest version of the docs. Users who need download versions can navigate to them.

**Comment by maxcellent** [comment]
hi, can you try this link? Note, in the middle of the url it's `/doc/ ` rather than `/static/`

https://www.javadoc.io/doc/org.owasp.esapi/esapi/latest/index.html

Feel free to reopen if you see more issues.
