### ISSUE TITLE
`aeron-archive` module is missing for `io.aeron` group

### ISSUE THREAD

**Issue by vyazelenko** [maxcellent/javadoc.io#179]
Currently [io.aeron](https://javadoc.io/doc/io.aeron) list only the following modules:
![aeron-javadoc-modules](https://github.com/maxcellent/javadoc.io/assets/696855/69d28700-4799-4745-9b54-5baa2332a7de)

However it is missing another module `aeron-archive`. It seems that this module is missing in all of the published versions.
Looking at the latest [published artifacts](https://repo1.maven.org/maven2/io/aeron/aeron-archive/1.42.0/) on Maven Central I can see that it contains the javadoc jar.
![aeron-archive-artifacts](https://github.com/maxcellent/javadoc.io/assets/696855/9c39486f-4c6f-4721-8a2f-9826165a53b9)

Any clues why it might be missing?

**Comment by maxcellent** [comment]
https://javadoc.io/doc/io.aeron/aeron-archive

You would need to manually goto the line for the first time :)
