### ISSUE TITLE
mongodb-driver-core javadoc missing

### ISSUE THREAD

**Issue by jyemin** [maxcellent/javadoc.io#18]
For `org.mongodb:mongodb-driver-core:3.8.2` it says "No JavaDoc is released with artifact org.mongodb:mongodb-driver-core:3.8.2. Please try other versions." However, javadoc was released with that artifact: http://central.maven.org/maven2/org/mongodb/mongodb-driver-core/3.8.2/

**Comment by maxcellent** [comment]
This doesn't look like a valid jar, as it only has a size of 261 bytes. 

```
mongodb-driver-core-3.8.2-javadoc.jar             2018-09-19 13:36       261  
```

**Comment by jyemin** [comment]
I don't know what happened there.  But 3.9.x and 3.10.x javadoc jars look fine.  Sorry for the false alarm.
