### ISSUE TITLE
Web server is down

### ISSUE THREAD

**Issue by scordio** [maxcellent/javadoc.io#180]
![Screenshot 2023-10-03 at 23 17 13](https://github.com/maxcellent/javadoc.io/assets/26772046/cdd9ba3d-06c8-42e7-965f-2d80b29d17a8)

**Comment by lprimak** [comment]
Down for me as well

**Comment by lprimak** [comment]
This is a big deal. Is there any way I can help?

**Comment by NotMyFault** [comment]
Is there anything we can do to assist you @maxcellent to bring javadoc.io back? It has become a crucial part for many of us, yet it appears, there's only so little we can do to help out 😔

**Comment by dblock** [comment]
~Looks like @maxcellent hasn't been active on GitHub in 5 years :(~

**Comment by armanbilge** [comment]
That's not correct, they are active and have responded to other similar outages e.g. https://github.com/maxcellent/javadoc.io/issues/115#issuecomment-1413669645.

**Comment by maxcellent** [comment]
apologize guys. My old credit card was expired. The server is now restored.

**Comment by dblock** [comment]
@maxcellent want to setup a GitHub sponsors and extend the registration for some many years? I’ll contribute.

Also maybe there’s a foundation or someone else you want to donate this to? or some kind of backup, for who could at least have your credentials to keep this up in the unlikely case you can’t. Also happy to help with that.
