### ISSUE TITLE
Documentation page for common-fileupload2 is not available

### ISSUE THREAD

**Issue by freelancer-nguyen** [maxcellent/javadoc.io#181]
Following link from apache common fileupload page
https://javadoc.io/doc/org.apache.commons/commons-fileupload2

Has no content

**Comment by maxcellent** [comment]
so in this folder https://repo1.maven.org/maven2/org/apache/commons/commons-fileupload2/2.0.0-M1/

There is no binary jar, no javadoc jar. Surely that's expected?

**Comment by maxcellent** [comment]
I will close this for now.
