### ISSUE TITLE
Getting spurious 403s from builds that call javadoc.io

### ISSUE THREAD

**Issue by ascopes** [maxcellent/javadoc.io#182]
I've got a number of builds for Maven projects running in parallel and each project will attempt to generate JavaDocs by referencing pages on Javadoc.io.

I've had two or three failed builds in the past hour or so due to javadoc.io spuriously returning 403s. Reruns fix the issue, but this is resulting in flaky builds on my side.

Would it be possible to look into this? 403 sounds like it might be related to a WAF or something similar blocking some requests, since the site doesn't require authentication to access it usually.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.2:jar (default-cli) on project java-compiler-testing: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1
[ERROR] error: Error fetching URL: https://javadoc.io/doc/org.jspecify/jspecify/0.3.0/ (java.io.IOException: Server returned HTTP response code: 403 for URL: https://javadoc.io/doc/org.jspecify/jspecify/0.3.0/package-list)
[ERROR] 1 error
[ERROR] 4 warnings
[ERROR] Command line was: /opt/hostedtoolcache/Java_Zulu_jdk/21.0.1-12/x64/bin/javadoc @options @packages @argfile
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/runner/work/java-compiler-testing/java-compiler-testing/java-compiler-testing/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.6.2:jar (default-cli) on project java-compiler-testing: MavenReportException: Error while generating Javadoc: 
Exit code: 1
error: Error fetching URL: https://javadoc.io/doc/org.jspecify/jspecify/0.3.0/ (java.io.IOException: Server returned HTTP response code: 403 for URL: https://javadoc.io/doc/org.jspecify/jspecify/0.3.0/package-list)
1 error
4 warnings
Command line was: /opt/hostedtoolcache/Java_Zulu_jdk/21.0.1-12/x64/bin/javadoc @options @packages @argfile
```

This is being run from vanilla community GitHub action runners, so no proxy or other stuff should be sitting in the way that that most projects on GitHub wouldn't also be using.

**Comment by maxcellent** [comment]
It looks like for this jar only `element-list` is available: https://javadoc.io/doc/org.jspecify/jspecify/0.3.0/element-list

More details: https://stackoverflow.com/questions/49457896/cant-link-to-jdk10-in-javadoc-comments
