### ISSUE TITLE
JavaDoc not opening on browser from 4.0.0.Beta1 version onwards and including for resteasy-jaxrs

### ISSUE THREAD

**Issue by dhanashreekamali** [maxcellent/javadoc.io#185]
![image](https://github.com/maxcellent/javadoc.io/assets/49809529/f778e6cb-d041-4cf8-8349-7ff85b126b64)
Link: https://javadoc.io/doc/org.jboss.resteasy/resteasy-jaxrs/4.0.0.Beta1/index.html

**Comment by maxcellent** [comment]
This is because there is no javadoc jar published in the repo
- https://repo1.maven.org/maven2/org/jboss/resteasy/resteasy-jaxrs/4.0.0.Beta5/

For earlier version there is javadoc.jar published:
- https://repo1.maven.org/maven2/org/jboss/resteasy/resteasy-jaxrs/3.15.6.Final/
