### ISSUE TITLE
javadoc.io down again

### ISSUE THREAD

**Issue by nitin065** [maxcellent/javadoc.io#189]
[Server Down](https://javadoc.io/)
![image](https://github.com/maxcellent/javadoc.io/assets/20437084/08a8f4c6-2e85-4b1d-9b9f-fee9651a93cb)

**Comment by lprimak** [comment]
Anything we can do to help out with stability of the side?
Javadoc generation fails due to reference of javadoc.io if it's down

**Comment by nitin065** [comment]
It is up now. Maybe we need to find the root cause behind why it is occasionally going down.

**Comment by maxcellent** [comment]
It looks like the Threadpool has queued up so many tasks which caused OutOfMemoryError. 

I have capped Threadpool size and hopefully this will solve the issue.

**Comment by lprimak** [comment]
It’s down again. Sorry the fix probably didn’t work

**Comment by maxcellent** [comment]
> It’s down again. Sorry the fix probably didn’t work

yea I was waiting for weekend to deploy because weekdays' traffic is usually 10x bigger. Unfortunately the issue triggered again before deploy. Now the fix is in.
