### ISSUE TITLE
Keep protocol on forward

### ISSUE THREAD

**Issue by Vampire** [maxcellent/javadoc.io#19]
Requesting `https://www.javadoc.io/page/com.discord4j/Discord4J/2.10.1/package-list` answers with a 303 and location header `http://static.javadoc.io/com.discord4j/Discord4J/2.10.1/package-list`.
The browser nevertheless requests this via HTTPS, I guess because of the `Strict-Transport-Security: max-age=15552000; includeSubDomains` header.
But other tools like Java and thus also the JavaDoc tool do not follow cross-protocol redirects due to security considerations.
So to use javadoc.io for the `-link` option of the JavaDoc tool, you cannot follow the documented URL on javadoc.io, but instead you either have to directly use the static.javadoc.io URL or an HTTP URL.

It would be nice if the redirect `Location` headers would follow the protocol of the original request.

**Comment by maxcellent** [comment]
This should no longer be an issue as now all http requests are redirected to https.

**Comment by Vampire** [comment]
Well, with this you broke it the other way around.
Because of this issue I used `http` links and now they redirect to `https` links.
The same problem applies, protocol change is not supported and thus tools cannot use it. :-(
