### ISSUE TITLE
docs not being generated

### ISSUE THREAD

**Issue by abuchanan-airbyte** [maxcellent/javadoc.io#193]
I've visited a few versions of the java docs, for example for 6.12.1 https://www.javadoc.io/doc/io.fabric8/kubernetes-model/6.12.1/index.html

I get the message:
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/a0998136-e586-4751-bc22-661f2f05dd29">

It's been over 12 hours now, so I'm letting you know 😄 

Seems to apply to multiple versions, such as https://javadoc.io/doc/io.fabric8/kubernetes-model/latest/index.html as well

**Comment by maxcellent** [comment]
hi, 

The way javadoc.io works is to unpack the disted javadoc.jar. However, it looks like kubernetes-model-6.13.2-javadoc.jar is not really disted to maven. You can check here: https://repo1.maven.org/maven2/io/fabric8/kubernetes-model/6.13.3/

Max
