### ISSUE TITLE
Redirect `element-list`

### ISSUE THREAD

**Issue by ParadoxV5** [maxcellent/javadoc.io#194]
Currently, only [`latest/element-list`](https://javadoc.io/doc/org.jetbrains/annotations/latest/element-list) redirects to [`X.Y.Z/element-list`](https://javadoc.io/doc/org.jetbrains/annotations/24.1.0/element-list), while [`X/element-list`](https://javadoc.io/doc/org.jetbrains/annotations/24/element-list) and [`X.Y/element-list`](https://javadoc.io/doc/org.jetbrains/annotations/24.1/element-list) both 403.
I fell for this trap and it lead to [innocent failures](https://github.com/ParadoxV5/template-java-maven/actions/runs/10032548543/job/27724425909).

Supporting this would allow the URL to match pessimistic versioning (e.g., dependency with `<version>[24.0,25.0)</version>`).
It’s also inconsistent with how everything else redirects (e.g., [docs of class](https://javadoc.io/doc/org.jetbrains/annotations/24/org/jetbrains/annotations/NotNull.html)es, [the index](https://javadoc.io/doc/org.jetbrains/annotations/24/index-all.html)).

**Comment by maxcellent** [comment]
hello, do you have a sample library for me to check?

**Comment by ParadoxV5** [comment]
I don’t have a *simple* library, so I linked [JetBrains Annotations](https://github.com/JetBrains/java-annotations) as the example above.
Here’re the links again in plain:
* Redirects to https://javadoc.io/doc/org.jetbrains/annotations/24.1.0/element-list
  * https://javadoc.io/doc/org.jetbrains/annotations/latest/element-list
* Currently 403
  * https://javadoc.io/doc/org.jetbrains/annotations/24/element-list
  * https://javadoc.io/doc/org.jetbrains/annotations/24.1/element-list

**Comment by maxcellent** [comment]
There isn't a version called `24`. `24.0.0` is valid version. so the following link will work. Am I missing something?

https://javadoc.io/doc/org.jetbrains/annotations/24.0.0/element-list

**Comment by ParadoxV5** [comment]
https://javadoc.io/doc/org.jetbrains/annotations/24/org/jetbrains/annotations/NotNull.html
redirects to
https://javadoc.io/doc/org.jetbrains/annotations/24.1.0/org/jetbrains/annotations/NotNull.html
and
https://javadoc.io/doc/org.jetbrains/annotations/24/index-all.html
redirects to
https://javadoc.io/doc/org.jetbrains/annotations/24.1.0/index-all.html

These mean `24` is a valid major version and its latest minor/teeny version is `24.1.0`.

> Am I missing something?

The point of using the pessimistic versioning of `24` over the pinned `24.1.0` is that it will automatically change its redirect to `24.1.1`, `24.2.0` or etc when they’re released.

**Comment by maxcellent** [comment]
good point. I will try to support this redirection
