### ISSUE TITLE
Allow default Java user agent

### ISSUE THREAD

**Issue by oliviercailloux** [maxcellent/javadoc.io#20]
As indicated [here](https://stackoverflow.com/q/33866209), the javadoc tool must be told to change its User Agent, for the default one seems to be forbidden access to javadoc.io. And as indicated in a comment, the workaround of changing the default user agent for the javadoc tool doesn’t seem to work any more (that part is obviously not your fault).

Please consider hosting the service with a provider that does not exclude default Java user agent, for simpler (or even for possible!) access to the service.

(Not sure if this issue relates to  #17, I suppose not, as that one is closed.)

**Comment by maxcellent** [comment]
This is unfortunately a limitation of Cloudflare. It seems there is no way from Dashboard to whitelist a specific user agent

I am reaching out them to seek for a solution. If this cannot be workarounded, then will add SO hacks to homepage as a reference to other developers.

**Comment by maxcellent** [comment]
This unfortunately cannot be easily workarounded with cloudflare. 

I am trying to switch to AWS cloudfront.

**Comment by maxcellent** [comment]
Unfortunately AWS cloudfront is not an option because they don't provide SSL solution. I have linked SO from homepage though.

**Comment by maxcellent** [comment]
In fact, Cloudflare guys helped solving the issue. 

```
curl -I -A "Java/1.6.0_14" https://static.javadoc.io/org.checkerframework/checker-qual/2.2.2/package-list
HTTP/1.1 200 OK
Date: Mon, 08 Apr 2019 13:06:04 GMT
Content-Type: text/plain
```

**Comment by abhin4v** [comment]
I'm using maven to generate javadocs and I'm running into the same issue. This is my maven javadoc plugin config:

    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.1.0</version>
        <configuration>
            <links>
                <link>https://static.javadoc.io/org.asynchttpclient/async-http-client/2.9.0/</link>
            </links>
        </configuration>
    </plugin>

I get this error when I run the javadoc generation with maven in debug mode:

    [DEBUG] Could not follow https://static.javadoc.io/org.asynchttpclient/async-http-client/2.9.0/. Reason: Unexpected HTTP status code 403 getting resource https://static.javadoc.io/org.asynchttpclient/async-http-client/2.9.0/.

**Comment by abhin4v** [comment]
I have narrowed it down to the the [`followLinks`](https://github.com/apache/maven-javadoc-plugin/blob/maven-javadoc-plugin-3.1.0/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java#L6333) method in the maven-javadoc-plugin. The javadoc says:

     /**
     * Follows all of the given links, and returns their last redirect locations. Ordering is kept.
     * This is necessary because javadoc tool doesn't follow links, see JDK-8190312 (MJAVADOC-427, MJAVADOC-487)
     *
     * @param links Links to follow.
     * @return Last redirect location of all the links.
     */

But hitting a URL like `https://static.javadoc.io/org.asynchttpclient/async-http-client/2.9.0/` returns a 403 response instead of the `index.html` page as other HTTP servers generally do. 

So the solution would be to configure the server serving `static.javadoc.io` to return the `index.html` files corresponding to the valid URLs ending with `/`.
