### ISSUE TITLE
Certain javadocs no longer resolvable via static.javadoc.io

### ISSUE THREAD

**Issue by ljnelson** [maxcellent/javadoc.io#23]
Consider this:

https://javadoc.io/doc/jakarta.persistence/jakarta.persistence-api/2.2.2

When hit with a browser, you get javadocs in HTML format.  Fine.

Normally one may also hit this:

https://static.javadoc.io/jakarta.persistence./jakarta.persistence-api/2.2.2

…but for this project (and many others with what looks like JDK 9+ javadocs) this doesn't work.

Contrast that with this:

https://javadoc.io/doc/org.eclipse.microprofile.config/microprofile-config-api/1.3

…and:

https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3

…which works fine.

**Comment by ljnelson** [comment]
Another arbitrary example:

https://static.javadoc.io/org.jboss.weld.environment/weld-environment-common/3.1.1.Final gives a 403.

**Comment by maxcellent** [comment]
with `static` domain you have to refer to the page directly: https://static.javadoc.io/org.jboss.weld.environment/weld-environment-common/3.1.1.Final/index.html

closing now. Feel free to reopen if you have more issues

**Comment by ljnelson** [comment]
OK, I will reopen this—well, no, I'll file a new bug.

You can obviously make your tool do whatever you want it to; I have no control over that.  I hope that I can eventually convince you that `javadoc` and the `maven-javadoc-plugin` all need the following resources to NOT give any kind of error (and I personally don't care whether it's `static.javadoc.io` or not):

* https://static.javadoc.io/some.groupId/some-artifact-id/some-version
* https://static.javadoc.io/some.groupId/some-artifact-id/some-version/
* https://static.javadoc.io/some.groupId/some-artifact-id/some-version/package-list
* https://static.javadoc.io/some.groupId/some-artifact-id/some-version/package-list/ # must refer to the same resource as the line above does
* https://static.javadoc.io/some.groupId/some-artifact-id/some-version/element-list
* https://static.javadoc.io/some.groupId/some-artifact-id/some-version/element-list/ # must refer to the same resource as the line above does

I said "any kind of error" but I should say that in the case of `element-list` vs. `package-list`: `element-list` is what JDK 9+'s `javadoc` looks for first, and if it can't find it (404, which your tool does not return) then it looks for `package-list` instead.

There will always be a `package-list` resource in any javadocs generated by the `javadoc` tool.  It must also be able to be addressed via `package-list/`.
