### ISSUE TITLE
javadoc.io/page URL redirected to a wrong version

### ISSUE THREAD

**Issue by Atry** [maxcellent/javadoc.io#24]
I expect https://javadoc.io/page/com.thoughtworks.dsl/dsl_2.11/1.4.0/index.html should redirect to https://static.javadoc.io/com.thoughtworks.dsl/dsl_2.11/1.4.0/index.html. Unfortunately it currently redirects to https://static.javadoc.io/com.thoughtworks.dsl/dsl_2.11/1.4.0%2B6-4fbcea79/index.html .

**Comment by maxcellent** [comment]
fixed and deployed
