### ISSUE TITLE
javadoc.io hijacked?

### ISSUE THREAD

**Issue by NoelJB** [maxcellent/javadoc.io#25]
Are you still maintaining javadoc.io?  As of at least today, it appears to have been hijacked:

"This domain was recently registered at Namecheap. Please check back later!"

;; ANSWER SECTION:
www.javadoc.io. 1722 IN A 198.54.117.199
www.javadoc.io. 1722 IN A 198.54.117.198
www.javadoc.io. 1722 IN A 198.54.117.197
www.javadoc.io. 1722 IN A 198.54.117.200

**Comment by JanecekPetr** [comment]
For future reference: https://www.whois.com/whois/javadoc.io

>>>
## Domain Information
Domain: javadoc.io  
Registrar: NameCheap, Inc  
Registered On: 2014-07-07  
Expires On: 2020-07-07  
Updated On: 2019-07-22  
>>>

**Comment by maxcellent** [comment]
domain is expired. 

I have renewed and will auto-renew in the future.
