### ISSUE TITLE
4 day old project on maven central still not showing up

### ISSUE THREAD

**Issue by giltene** [maxcellent/javadoc.io#26]
org.heaputils:HeapUseWatcher has been on Maven Central for 4 days now:
https://search.maven.org/artifact/org.heaputils/HeapUseWatcher/1.0.1/jar

But javadoc.io does not show it yet...

**Comment by maxcellent** [comment]
You will need to manually enter the link on your url for the first time. New versions will then be picked up automatcially.

https://javadoc.io/doc/org.heaputils/HeapUseWatcher/1.0.1
