### ISSUE TITLE
Homepage refer to an old and deprecated mockito artefact

### ISSUE THREAD

**Issue by bric3** [maxcellent/javadoc.io#28]
As of today, the javadoc.io give url example using an old and deprecated mockito artefact.

> Link to a particular class
> You can link to a particular class with url javadoc.io/page/{org}/{artifact}/{version}/{page}
> 
>     For example: https://javadoc.io/page/org.mockito/mockito-all/1.10.8/org/mockito/stubbing/Answer.html
> 
> For latest version just put latest in your url javadoc.io/page/{org}/{artifact}/latest/{page}
> 
>     For example: https://javadoc.io/page/org.mockito/mockito-all/latest/org/mockito/stubbing/Answer.html
> 
> For latest patch version for a specific major version javadoc.io/page/{org}/{artifact}/{major_version}/{page}
> 
>     For example: https://javadoc.io/page/org.mockito/mockito-all/2.0/org/mockito/stubbing/Answer.html will be redirected to 2.0.2-beta (the current latest 2.0.x version)

Is it possible to replace those with **mockito-core** artefact, and using a modern version, respectively:

* https://javadoc.io/page/org.mockito/mockito-core/3.0.0/org/mockito/stubbing/Answer.html
* https://javadoc.io/page/org.mockito/mockito-core/latest/org/mockito/stubbing/Answer.html
* https://javadoc.io/page/org.mockito/mockito-core/3.0/org/mockito/stubbing/Answer.html

**Comment by maxcellent** [comment]
sure, I can make the change. Although this is really just an example. :)

**Comment by bric3** [comment]
@maxcellent I'd rather have an example with an up-to-date lib than an old one. Anyway that would be much appreciated, thank you in advance.

**Comment by maxcellent** [comment]
this is no longer an issue with the new homepage

**Comment by bric3** [comment]
@maxcellent Cool, thanks for the feedback !
And nice new homepage !
