### ISSUE TITLE
Currently showing broken Badge

### ISSUE THREAD

**Issue by khmarbaise** [maxcellent/javadoc.io#30]
Hi, currently using the following information:

[![javadoc.io](https://javadoc.io/badge/org.apache.maven.plugins/maven-install-plugin/javadoc.io.svg)](https://javadoc.io/doc/org.apache.maven.plugins/maven-install-plugin)

which results in: 404 badge not found
Can looked at:
https://github.com/apache/maven-install-plugin/tree/MINSTALL-162
![javadoc-issue](https://user-images.githubusercontent.com/42484/67145344-3414eb80-f281-11e9-8ad9-aa0603302362.png)

The link behind it seemed to be working fine...so clicking on the images works...

BTW: Nice tool

**Comment by maxcellent** [comment]
hi, thanks for reporting this. This is fixed now.

**Comment by khmarbaise** [comment]
Hi,
thanks for the feedback. Works fine now. see ... Great. 

![javadoc-links](https://user-images.githubusercontent.com/42484/67148041-0b99eb00-f29b-11e9-88a0-1159f7500ccb.png)

**Comment by maxcellent** [comment]
no problem.

If you want, you could consider using following MD to always point to the
latest version

[![javadoc.io](
https://javadoc.io/badge2/org.apache.maven.plugins/maven-install-plugin/javadoc.io.svg)](https://javadoc.io/doc/org.apache.maven.plugins/maven-install-plugin
)

will be rendered as:

[image: image.png]
