### ISSUE TITLE
Badge / version sort order broken?

### ISSUE THREAD

**Issue by marco-schmidt** [maxcellent/javadoc.io#31]
Hi!

Both the badge at https://github.com/marco-schmidt/am and the first link at https://javadoc.io/doc/com.github.marco-schmidt/am show version 0.0.3 although there were versions 0.0.4 to 0.0.6 and most recent 0.1.0, which I would expect in both contexts to be displayed. All versions are available in the version drop-down, but 0.0.3 is first and likely therefore the default for both badge and drop-down menu. Any idea how I could have the most recent version shown? This worked up to and including 0.0.6, if I remember correctly.

Greetings and thanks for hosting javadoc.io,
Marco

**Comment by maxcellent** [comment]
Thanks for reporting. It's a bug when onboarding Bintray.  Raised #32 to fix

It sounds overkill, but if you happen to release a new version it will fix your issue. 

Otherwise you can use this markdown for now: 

`[![javadoc.io](https://javadoc.io/badge2/com.github.marco-schmidt/am/0.1.0/javadoc.io.svg)](https://javadoc.io/doc/com.github.marco-schmidt/am/0.1.0)`

**Comment by rohaniadnan** [comment]
> Hi!
> 
> Both the badge at https://github.com/marco-schmidt/am and the first link at https://javadoc.io/doc/com.github.marco-schmidt/am show version 0.0.3 although there were versions 0.0.4 to 0.0.6 and most recent 0.1.0, which I would expect in both contexts to be displayed. All versions are available in the version drop-down, but 0.0.3 is first and likely therefore the default for both badge and drop-down menu. Any idea how I could have the most recent version shown? This worked up to and including 0.0.6, if I remember correctly.
> 
> Greetings and thanks for hosting javadoc.io,
> Marco

Hi guys please do not upload anything that contained bugs and etc I hope that you are well understood that this is not supposed to be done. I reiterated again please do not upload anything that has bugs or so on. I hope u understand my deeper meaning. If you are not happy write back here. I am very happy to give you assistant.

**Comment by maxcellent** [comment]
fixed
