### ISSUE TITLE
No JavaDoc is released for artifact

### ISSUE THREAD

**Issue by andresouza-hotmart** [maxcellent/javadoc.io#34]
Hi, all.

I was looking for the docs for the artifact below. Since I couldn't find it, I followed the link to report and landed here.

`org.springframework.cloud:spring-cloud-starter-openfeign:1.4.7.RELEASE`

Do you know where this documentation is located?

Thank you and best regards!

-- Andre

**Comment by maxcellent** [comment]
hi, 

I can see the javadoc.jar is disted to maven central however the jar doesn't contain anything. The expectation is there is always an `index.html` packed in the jar. So the system is actually behaving as expected (given there is indeed nothing to show). 

Close the ticket now. Let me know if this is not expected. 

Max

https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-starter-openfeign/1.4.7.RELEASE/
