### ISSUE TITLE
Support different badge styles

### ISSUE THREAD

**Issue by gastaldi** [maxcellent/javadoc.io#35]
The badge URL (eg. https://javadoc.io/badge2/io.quarkus/quarkus-core/javadoc.svg) redirects to img.shields.io, which support different badge styles (by providing the `styles` query parameter).

It would be nice if the Javadoc badge supported that

**Comment by maxcellent** [comment]
deployed. you can append style param directly:

https://javadoc.io/badge2/io.quarkus/quarkus-core/javadoc.svg?style=for-the-badge
