### ISSUE TITLE
antlr4 version 4.8 is missing

### ISSUE THREAD

**Issue by martinda** [maxcellent/javadoc.io#37]
Antlr4 version 4.8 is missing. Is this something users like me can remedy?
Maven: https://mvnrepository.com/artifact/org.antlr/antlr4-runtime/4.8

**Comment by maxcellent** [comment]
this is working now after I click the `retry` button. 

closing the ticket now, let me know if there are more issues: https://javadoc.io/doc/org.antlr/antlr4-runtime/4.8/index.html
