### ISSUE TITLE
support for `-groovydoc.jar` artifacts

### ISSUE THREAD

**Issue by dlukyanov** [maxcellent/javadoc.io#38]
the groovy plugin for gradle builds by default `groovydoc.jar` artifact for documentation with absolutely same structure as javadoc.

could it be possible to add a support for it?

**Comment by dlukyanov** [comment]
just an example
https://jcenter.bintray.com/acme/groovy/acmejson/20200120/

**Comment by maxcellent** [comment]
what would be the structure of a groovydoc? I opened this jar file but there is nothing inside it? How do you expect javadoc.io to render this doc?

**Comment by dlukyanov** [comment]
right. here is another example. 
the documentation is not perfect but at least it present...
https://jcenter.bintray.com/acme/groovy/acmehttp/20190413/

**Comment by maxcellent** [comment]
thanks this makes more sense

**Comment by maxcellent** [comment]
hi @dlukyanov , 

The development is largely done. But there are more issues coming out when I am testing it. 

We use maven-metadata.xml to resolve all versions in maven. eg, https://jcenter.bintray.com/acme/groovy/acmehttp/maven-metadata.xml 

However from the file listed above, only 20.04.27 is in the version list. Is this always the case for groovy libraries? 

Max

**Comment by dlukyanov** [comment]
Hey Max,

No, just one version was published with correct versioning rules, but all other versions are there and nothing to do with them )

Regards,
  Dmitry


05 July 2020, 07:16:04, by "Max Zhu" <notifications@github.com>:

hi @dlukyanov ,

The development is largely done. But there are more issues coming out when I am testing it.

We use maven-metadata.xml to resolve all versions in maven. eg, https://jcenter.bintray.com/acme/groovy/acmehttp/maven-metadata.xml

However from the file listed above, only 20.04.27 is in the version list. Is this always the case for groovy libraries?

Max

**Comment by shadycuz** [comment]
@maxcellent I would also love to host my groovy docs on javadoc.io =)

**Comment by maxcellent** [comment]
I guess it's my bad that this issue has been outstanding for so long. But when I check the groovy dist I do see a proper `javadoc.jar` file is published. For example,

```https://repo1.maven.org/maven2/org/grails/grails-core/4.0.1/```

@dlukyanov your example is no longer working because it's overwritten by a new version written in java: `20.04.27`. Do you have more examples? @shadycuz you are also welcome to advise

**Comment by shadycuz** [comment]
@maxcellent Yes it works for javadoc.jar but its not straightforward to get your build tool to produce javadoc if its configured for groovy. 

If the format of the doc jars are the same, I think the ask here is that the groovydoc.jar gets treated like a javadoc.jar. I have mine setup and working to product the javadoc.jar but it might help others in the future.

**Comment by maxcellent** [comment]
@shadycuz I have finished dev work locally. All I need is something to test. Do you have some sample groovy lib where only groovydoc.jar is published?

**Comment by shadycuz** [comment]
@maxcellent Do you only need me to send you the groovydoc.jar file? I can probably generate one real quick but my current library is not set to publish a groovydoc.jar to maven central, only the javadoc.jar.

**Comment by maxcellent** [comment]
ideally some published groovy library which doesn't generate `javadoc.jar` at all

**Comment by shadycuz** [comment]
I don't know when I will get a chance to do it. Possibly this weekend?

**Comment by shadycuz** [comment]
@dlukyanov 

Can you provide your build.gradle? 

I can no longer get my project to produce a groovydoc.jar. 

Running `gradle clean groovyDoc` only produces the html and not the jar file.

**Comment by maxcellent** [comment]
closing this for now. 

Feel free to re-open when you have more examples to test with
