### ISSUE TITLE
Access top package-list of com.nimbusds oauth sdk

### ISSUE THREAD

**Issue by codrblack** [maxcellent/javadoc.io#39]
https://javadoc.io/doc/com.nimbusds/oauth2-oidc-sdk/7.3/package-list
Access to the linked  package-list ist denied. Could you do anything here?

**Comment by maxcellent** [comment]
this is because only ```element-list``` is published for this library. 

https://javadoc.io/doc/com.nimbusds/oauth2-oidc-sdk/7.3/element-list
