### ISSUE TITLE
'Download' option doesn't work for alternative version formats (AccessDenied)

### ISSUE THREAD

**Issue by koczadly** [maxcellent/javadoc.io#40]
Downloading the javadoc jar from javadoc.io (using the button at the top of the page) appears to fail with artifact versions containing the hyphen character (and possibly others).

**Example:** The download button at the top of [this page](https://www.javadoc.io/doc/uk.oczadly.karl/jnano/latest/overview-summary.html) links to [this download url](https://www.javadoc.io/jar/uk.oczadly.karl/jnano-2.0.1-V20-javadoc.jar), which returns an AccessDenied error. Artifacts without the hyphened version appear to download as expected.

**Comment by maxcellent** [comment]
fixed and deployed

**Comment by koczadly** [comment]
Awesome, thanks mate! Really love and appreciate the service you created, it's helped me out countless times.

**Comment by maxcellent** [comment]
cheers :) happy to hear that!
