### ISSUE TITLE
the javadoc artifact not found on jcenter

### ISSUE THREAD

**Issue by dlukyanov** [maxcellent/javadoc.io#41]
Getting error

> Artifact acme.groovy:acmetemplate does not exist

for https://javadoc.io/doc/acme.groovy/acmetemplate/20200328

however the artifact is present on jcenter:

https://jcenter.bintray.com/acme/groovy/acmetemplate/20200328/

**Comment by maxcellent** [comment]
It looks like [maven-metadata.xml](https://jcenter.bintray.com/acme/groovy/acmetemplate/maven-metadata.xml) doesn't contain any version like ```20200328```, which is not expected according to [apache doc](https://maven.apache.org/ref/3.6.2/maven-repository-metadata/)

I am not sure if this is project specific or down to groovy though?

**Comment by dlukyanov** [comment]
strange. 
i used javadoc this time as a base gradle task.
i'm not actually managing this file when publishing artifacts...
the project and this file is managed by bintray.com
going to check if i could update it with bintray api 
in any case it's better to provide the detailed error message what exactly is missing..

truthfully, with maven/gradle/ivy you could download this dependency without maven-metadata.xml  file, so maybe if version defined correctly you don't really need it?

**Comment by maxcellent** [comment]
It has always been the case for other libraries that ```maven-metadata.xml``` lists out all available versions. 

That's why I am really curious how is this time different. Please keep me updated if you have any findings with bintray.

**Comment by dlukyanov** [comment]
Got reply from jfrog:

With regards to your query on the problem with updating the maven-metadata.xml file, the version format you are using does not fit the maven comparator system and when the meta-data index calculation job runs in the background looks for versions that begin with 8 digits (most likely timestamps) and filters out. In your case, the version number is named “20180723” which results in the meta-data calculation failing.

In order to avoid this, please follow the below link on naming the version according to the maven naming convention:
https://maven.apache.org/guides/mini/guide-naming-conventions.html

----

So, I'm going to change versioning approach...

And please add some details to error message.

Thanks!

**Comment by dlukyanov** [comment]
the problem that 8 digits in a row in version considered as a nightly build by bintray.
changed  version format and now everything works fine

**Comment by maxcellent** [comment]
thanks for the follow ups. 

I do agree the error message need to be improved though. (both javadoc.io and bintry!)

**Comment by maxcellent** [comment]
fyi the error message has been improved: https://javadoc.io/doc/javax.mail/javax.mail-api/1.4.4/index.html
