### ISSUE TITLE
the service is reporting that artifacts which are accompanied by javadoc jars don't supply javadoc

### ISSUE THREAD

**Issue by andyglick** [maxcellent/javadoc.io#42]
Looking at the central repository for spring-statemachine here https://search.maven.org/classic/#search%7Cga%7C1%7Cspring-statemachine

most of the jars have javadoc jars listed for the artifacts here are various messages from 3 different artifacts

even the javadoc jars that the service has reported being downloaded are not  being recognized by later attempts to access them This occurred on Firefox and Chrome on a Mac running Catalina

No JavaDoc is released for artifact org.springframework.statemachine:spring-statemachine-test:2.2.0.RELEASE. Please try other versions. You can retry or report to us if you believe this is not expected. 

org.springframework.statemachine:spring-statemachine-test:2.2.0.RELEASE - Javadoc is being downloaded. Normally this will be completed within 10 minutes. Please refresh page again later. Report to us if this isn't finished after a few hours 

No JavaDoc is released for artifact org.springframework.statemachine:spring-statemachine-starter:2.2.0.RELEASE. Please try other versions. You can retry or report to us if you believe this is not expected. 

org.springframework.statemachine:spring-statemachine-starter:2.2.0.RELEASE - Javadoc is being downloaded. Normally this will be completed within 10 minutes. Please refresh page again later. Report to us if this isn't finished after a few hours

No JavaDoc is released for artifact org.springframework.statemachine:spring-statemachine-autoconfigure:2.2.0.RELEASE. Please try other versions. You can retry or  report to us if you believe this is not expected.

org.springframework.statemachine:spring-statemachine-autoconfigure:2.2.0.RELEASE - Javadoc is being downloaded. Normally this will be completed within 10 minutes. Please refresh page again later. Report to us if this isn't finished after a few hours

**Comment by maxcellent** [comment]
[spring-statemachine-autoconfigure-2.2.0.RELEASE-javadoc.jar](https://search.maven.org/classic/remotecontent?filepath=org/springframework/statemachine/spring-statemachine-autoconfigure/2.2.0.RELEASE/spring-statemachine-autoconfigure-2.2.0.RELEASE-javadoc.jar) appears to be empty. 

To check it by yourself, you can rename the jar to zip and extract the content. In order to get it working with ```javadoc.io```, there need to be an ```index.html``` under the extracted root.

closing the issue now, let me know if there are more issues
