### ISSUE TITLE
[Kotlin, Dokka] No JavaDoc is released for artifact

### ISSUE THREAD

**Issue by RoRoche** [maxcellent/javadoc.io#43]
I get this message when trying to get Javadoc for my Kotlin libraries (javadoc with Dokka):

```
No JavaDoc is released for artifact com.github.roroche:eo-rest:0.0.1. Please try other versions.
```

when touching the following URL:

```
https://javadoc.io/doc/com.github.roroche/eo-rest/0.0.1/
```

The jar is properly distributed: https://repo1.maven.org/maven2/com/github/roroche/eo-rest/0.0.1/

But when extracting it, I see that the `index.html` file is not at the root directory, but in `eo-rest-0.0.1-javadoc/eo-rest` directory.

Is a fix possible?

**Comment by maxcellent** [comment]
unfortunately this is always the assumption. 

out of interest, how do you generate Kotlin javadoc?

**Comment by RoRoche** [comment]
Actually, Dokka generates a different file structure. I have to configure it to use the `javadoc` type instead of `html`:

```groovy
dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/javadoc"
}
```

So now it works for my new release: https://javadoc.io/doc/com.github.roroche/eo-rest/latest/index.html

To answer your question, I use [the following plugin ](https://plugins.gradle.org/plugin/org.jetbrains.dokka)such as:

```groovy
buildscript {
    ext {
        kotlin_version = '1.3.61'
    }
    dependencies {
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:0.10.1"
    }
}
```

And in my deployment, I configure 2 tasks:

```groovy
dokka {
    outputFormat = 'javadoc'
    outputDirectory = "$buildDir/dokka"
}

task dokkaJar(type: Jar) {
    group = JavaBasePlugin.DOCUMENTATION_GROUP
    description = "Assembles Kotlin docs with Dokka"
    archiveClassifier.set("javadoc")
    from dokka
    dependsOn dokka
}

artifacts {
    archives sourcesJar
    archives dokkaJar
}

publishing {
    publications {
        release(MavenPublication) {
            groupId PUBLISH_GROUP_ID
            artifactId PUBLISH_ARTIFACT_ID
            version project.version

            artifact("$buildDir/outputs/aar/${project.getName()}-release.aar")
            artifact sourcesJar
            artifact(tasks.getByName("dokkaJar"))
```

More details in my current side-project repo: https://github.com/RoRoche/elegant-android (see `build.gradle` file in the root directory and contents in the `publish` directory).

**Comment by maxcellent** [comment]
thanks for the detail @RoRoche

**Comment by olivier65** [comment]
So, when are you going to implement the suggestion? As of today there is still no documentation for mockito-android. That's quite a deterrent...

**Comment by maxcellent** [comment]
hi @olivier65 , have you tried @RoRoche 's solution?

For mockito-android is what you mean? https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html
