### ISSUE TITLE
Support all possible shields.io parameters

### ISSUE THREAD

**Issue by rxmicro** [maxcellent/javadoc.io#45]
The badge URL 

`https://javadoc.io/badge2/io.rxmicro/rxmicro/javadoc.svg?logo=java`

 redirects to

`https://img.shields.io/badge/javadoc-0.3-brightgreen.svg`

, which support different query parameters: `logo`, `color`, `style`, etc

It would be nice if the Javadoc badge supported all parameters expect `label` and `message`.

It seems that `style` parameter already supported (https://github.com/maxcellent/javadoc.io/issues/35),
but it would be great if other useful parameters will be supported as well.

I think that the simplest implementation of this task is to add all query parameters after `?` to the `Location` header

**Comment by LikeTheSalad** [comment]
It would be very useful for me if the param `label` gets supported as well!

Thanks.

**Comment by NthPortal** [comment]
you can change the label by changing the `javadoc.svg` at the end to `<label>.svg`. See for example: ![label](https://javadoc.io/badge2/io.rxmicro/rxmicro/label.svg?logo=java)

**Comment by maxcellent** [comment]
deployed. example:

https://javadoc.io/badge2/io.quarkus/quarkus-core/javadoc.svg?style=for-the-badge&color=yellow

**Comment by Mariaohuntman** [comment]
323908

**Comment by onacit** [comment]
@NthPortal My badge renders `404 | badge not found` when I change the `.../javadoc.svg` into `.../whatever.svg`. Can you please help me?

Oh.. the `whatever` part contains some hyphens(`-`)

**Comment by NthPortal** [comment]
@onacit not my repo
