### ISSUE TITLE
In case my project is hosted on both maven central and bintray, only the latest version from maven central is hosted

### ISSUE THREAD

**Issue by MohabMohie** [maxcellent/javadoc.io#46]
I use bintray to deploy early releases, and maven central repository to host stable ones.
Here's a snapshot from the latest releases
![image](https://user-images.githubusercontent.com/19201898/85255619-e7625f80-b462-11ea-8fd0-5b2c2fbd03e9.png)
javadoc.io will only detect the ones on maven
![image](https://user-images.githubusercontent.com/19201898/85255659-fcd78980-b462-11ea-94f4-230eff08f694.png)

Expected: it should detect both releases and show the latest one, or give an option to sync from bintray or sync from maven central

**Comment by maxcellent** [comment]
It doesn't seem this lib is released to bintray? https://jcenter.bintray.com/io/github/mohabmohie/SHAFT_ENGINE/maven-metadata.xml

Closing this for now. Feel free to reopen if you still have the issue after bintray is enabled.

**Comment by MohabMohie** [comment]
I think you're referring to this file, correct?
https://dl.bintray.com/mohabmohie/SHAFT/io/github/mohabmohie/SHAFT_ENGINE/:maven-metadata.xml
