### ISSUE TITLE
Remove cached config4k (0.4.2)

### ISSUE THREAD

**Issue by ihostage** [maxcellent/javadoc.io#47]
Can you remove the cached empty Javadoc artifact of `config4k-0.4.2` library? 🙏 
It was badly released to JCenter (with empty javadoc artifact) and then removed. 😞 
Now it published to Maven Central https://repo1.maven.org/maven2/io/github/config4k/config4k/0.4.2/

**Comment by maxcellent** [comment]
I can see this is not really empty: https://javadoc.io/doc/io.github.config4k/config4k/latest/index.html

Feel free to re-open if you still want to remove it.
