### ISSUE TITLE
Support JitPack

### ISSUE THREAD

**Issue by DeflatedPickle** [maxcellent/javadoc.io#48]
I use JitPack instead of Maven Central because of the verbosity Maven Central would bring to my `build.gradle`, and because Maven Central would add the need to hide secret keys.

It would be nice if artifacts on JitPack were supported. It works just like a Maven, that uses GitHub releases (or commits) to build the artifact.

**Comment by maxcellent** [comment]
Is JitPack still actively maintained? https://jitpack.io/#edvin/tornadofx is not giving me any result

![image](https://user-images.githubusercontent.com/2378229/86525463-feb93800-beb9-11ea-8539-316b81e05568.png)

**Comment by DeflatedPickle** [comment]
@maxcellent, I believe it is, but you can't just grab any repo, there are [setup steps](https://jitpack.io/docs/#publishing-on-jitpack) you have to do to get it on their maven. [Here's](https://jitpack.io/#DeflatedPickle/tosuto) one of my projects, it picks up the releases and commits as versions users can add in their builds.

But this is possibly pointless as it seems JitPack will also [host a `javadoc.jar` the project builds](https://jitpack.io/docs/#javadoc-publishing).

My bad for not seeing that. Should I close this?

**Quick edit**: TornadoFX gave me a few results.
![image](https://user-images.githubusercontent.com/24986480/86538992-4effbc80-bef1-11ea-9ee4-69a85ab9098f.png)

**Comment by maxcellent** [comment]
ok, it seems only working now.

sure, closing the issue now.
