### ISSUE TITLE
Latest version not always working?

### ISSUE THREAD

**Issue by marcelmay** [maxcellent/javadoc.io#49]
javadoc.io lists older version as latest, although a newer version is available (for months):

- javadoc.io reports 1.5.9 as latest version, although I would expect 1.5.14 as latest:
  https://javadoc.io/doc/com.icegreen/greenmail 

- javadoc.io does contain higher versions (but not listed as latest):
  https://javadoc.io/doc/com.icegreen/greenmail/1.5.14/index.html

- Maven central contains 1.5.14 (actual latest version):
  https://repo1.maven.org/maven2/com/icegreen/greenmail/maven-metadata.xml
  https://repo1.maven.org/maven2/com/icegreen/greenmail/1.5.14/

Thx alot!

**Comment by Marcono1234** [comment]
It appears the underlying issue might be that the ordering of versions is based on codepoints instead of the numeric values.
E.g. for https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind it opens 2.9.9.3 even though there is 2.9.10 and 2.10.
So the ordering likely considers **1**0 < 9.

**Comment by maxcellent** [comment]
fiexed. FYI javadoc.io will honor `metadata.xml` instead of  making a guess. eg,  https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/maven-metadata.xml

**Comment by kvnxiao** [comment]
@maxcellent How come the metadata.xml is not working for https://www.javadoc.io/doc/com.discord4j/discord4j-core/latest/index.html, the metadata.xml is https://repo1.maven.org/maven2/com/discord4j/discord4j-core/maven-metadata.xml

**Comment by maxcellent** [comment]
This is because this library is published to both JCenter and maven central with different versions: 

- https://repo1.maven.org/maven2/com/discord4j/discord4j-core/maven-metadata.xml
- https://jcenter.bintray.com/com/discord4j/discord4j-core/maven-metadata.xml

Let me think about it...

**Comment by maxcellent** [comment]
fixed

**Comment by marcelmay** [comment]
@maxcellent , the links show the previous version 1.5.13 now but I would expect latest version 1.5.14:

* Badge link: https://javadoc.io/badge2/com.icegreen/greenmail/javadoc.svg
* Javadoc link: https://javadoc.io/doc/com.icegreen/greenmail/latest/index.html

The latest version is available on javadoc.io:
https://javadoc.io/doc/com.icegreen/greenmail/1.5.14/index.html

But when selecting the version, it is listed at the bottom of the (sorted) versions?

**Comment by maxcellent** [comment]
@marcelmay any reason the latest version is only published to maven?

Additionally it looks like 1.5.14 was published on July 4th. However, 1.5.13 was published on July 15th?

- https://repo1.maven.org/maven2/com/icegreen/greenmail/maven-metadata.xml 
- https://jcenter.bintray.com/com/icegreen/greenmail/maven-metadata.xml

**Comment by marcelmay** [comment]
GreenMail only publishes to Maven Central (repo1.maven.org), where 1.5.13 was published in April and 1.5.14 in July:
https://repo1.maven.org/maven2/com/icegreen/greenmail/

JCenter syncs from Maven Center, I guess. I 'claimed' the artifacts just recently, and JCenter seems not in sync with Maven Central.

Is there a way to tell javadoc.io the primary repo location for projects?
I would assume Maven Central as primary location for Maven projects, priority wise.

Thx alot, @maxcellent !

**Comment by maxcellent** [comment]
I did some more magic and I think it should be covering your case now!

**Comment by marcelmay** [comment]
Works now, thanks a million!
