### ISSUE TITLE
[BUG] bintry javadoc is still not loaded

### ISSUE THREAD

**Issue by maxcellent** [maxcellent/javadoc.io#5]
javadoc.io page: https://www.javadoc.io/doc/com.kaltura.playkit/playkit/3.3.2
bintray page: 
https://bintray.com/kaltura/android/playkit/3.3.2
http://jcenter.bintray.com/com/kaltura/playkit/playkit/3.3.2/

**Comment by kaifox** [comment]
Dear all,

as we see that this issue is open for quite some time and we are very interested in this feature, we were wondering if we could help somehow in fixing this? It might still be simpler to help you there than to go the painful way and sync everything with maven central ;-)

@andreacalia, @kaifox

**Comment by Vampire** [comment]
I don't think releasing to to Maven Central is painful, but the point is, that some people prefer to deploy only to Bintray.
It would really be nice if also Bintray releases could be supported.

**Comment by dekalo-stanislav** [comment]
Yep, would be helpful for me too.

**Comment by maxcellent** [comment]
hi, this has been a while but finally the bintray is supported now. Feel free to re-open if you encountered any issue.

**Comment by Vampire** [comment]
@maxcellent if you close an issue, we cannot reopen it.
Only if the author himself closes the issue he can also reopen it.
Can you please reopen it, the support does not work properly.
Issues I found so far:
- Going to https://www.javadoc.io/doc/net.dv8tion/JDA/ shows the latest version on Maven Central, but there are newer versions on JCenter that are also **partly** listed in the version drop-down
- Selecting the latest listed version of the version drop-down https://www.javadoc.io/doc/net.dv8tion/JDA/4.0.0_46 says there is no JavaDoc released while it is as you can see at https://bintray.com/dv8fromtheworld/maven/JDA/#files/net/dv8tion/JDA/4.0.0_46. Pressing the "retry" link also does not load the JavaDoc
- Pressing the "sync latest version" button in the upper right brings you also to the latest Maven Central released version
- Going to the really latest version https://www.javadoc.io/doc/net.dv8tion/JDA/4.0.0_52 manually says, that this version does not exist. There it says latest is 4.0.0_46.

**Comment by maxcellent** [comment]
@Vampire 

1. I see. The way it works now is. If the jar doesn't exist in maven, it will fallback to JCenter. In your case, you have the library published to **both** maven and bintray. Any reason why they are out of sync? Wondering if it's a common use case.
2. It actually worked in the background. But I can not see an **index.html** after unzipped your -javadoc.jar. How do you generate jar? 
3. same reason as 1 
4. same reason as 2

**Comment by Vampire** [comment]
It is not my lib, it is a lib I depend upon and that I want to link my JavaDoc against using javadoc.io.

They released to Maven Central formerly and then switched to releasing to JCenter at some point. I don't know why, but it could well be the case for other libs too.

**Comment by maxcellent** [comment]
So if you download their jar and unzip it, you will see there is no index.html, which means it won't work with current implementation. 

Do you think you can reach out library owner to find out more? I highly doubt they are using `standard` approach to generate javadoc

**Comment by Vampire** [comment]
Actually for 4.0.0_52 the javadoc jar seems to be correct

**Comment by maxcellent** [comment]
ok, deployed an enhancement. Now it's able to resolve from multiple repos and merge versions.

**Comment by andreacalia** [comment]
@maxcellent thanks !
