### ISSUE TITLE
Redundant scrollbar when using Firefox

### ISSUE THREAD

**Issue by Marcono1234** [maxcellent/javadoc.io#51]
When using Firefox (version 78.0.2 (64-Bit)) there is a redundant scrollbar for the complete page:
![Example screenshot](https://user-images.githubusercontent.com/11685886/87886810-2a8efe80-ca20-11ea-9354-7b97a852c318.png)

This screenshot was taken for [jackson-databind](https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/latest/com/fasterxml/jackson/databind/introspect/AnnotatedClass.html), however it looks like all Javadocs are affected.
The window size apparently does not matter. When completely scrolling down with the outer scrollbar there is a small blank margin.

This issue does not occur with Microsoft's Chromium-based Edge browser.

**Comment by maxcellent** [comment]
fixed
