### ISSUE TITLE
Browser history navigation not working correctly

### ISSUE THREAD

**Issue by Marcono1234** [maxcellent/javadoc.io#52]
### Description
It appears that the browser history navigation (backward and forward arrows next to address bar) do not work correctly for:
- Firefox 78.0.2 (64-Bit)
- Microsoft Chromium-based Edge 84.0.522.40 (Official build) (64-bit)

The URL in the address bar changes but the page is not updated.

### Reproduction steps
1. Open for example [jackson-databind](https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.10.0/com/fasterxml/jackson/databind/introspect/AnnotatedClass.html)
2. Click on the link to any other type, e.g. `TypeResolutionContext`
3. Press the back / left browser navigation arrow near the address bar
:x: The URL in the address bar changes but the page is not updated.

**Comment by maxcellent** [comment]
fixed
