### ISSUE TITLE
Javadoc failing to resolve

### ISSUE THREAD

**Issue by MihaiBojin** [maxcellent/javadoc.io#53]
Hi, I am trying to add my project but it's failing to find the javadoc.

The jar is however released on Maven Central: https://repo1.maven.org/maven2/com/mihaibojin/props/props-core/0.0.3/props-core-0.0.3-javadoc.jar

Can you take a look, please?
Thank you!

**Comment by maxcellent** [comment]
hi, not sure how you generated javadoc. But I don't see an `index.html` file under the root directory of the javadoc folder.

**Comment by maxcellent** [comment]
closing it for now as this is considered an expected behavior. Feel free to reopen if you have more findings
