### ISSUE TITLE
Make "latest" a separate version

### ISSUE THREAD

**Issue by Marcono1234** [maxcellent/javadoc.io#54]
It appears when you select the currently latest version, e.g. for [Gson](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/module-summary.html) "2.8.6", it automatically changes the URL to <code>.../<b>latest</b>/...</code>. However, in some cases this is undesired, e.g. when you want to link to that exact version.

Would it be possible to add a separate "latest" version entry to the dropdown which:
- always appears as first entry
- is (if possible) differently formatted, e.g. italic, to make the user able to see that it is not a version name

And only if that "latest" version is selected use `latest` as version in the URL as well.

**Comment by maxcellent** [comment]
This is expected. In this case, `/latest/` and `/2.8.6/` are effectively the same page. Thus sharing the same URL. 

As a workaround, would manually updating the URL help? For example, in this case you can manually update to 2.8.6, which will always link to 2.8.6.

https://javadoc.io/doc/com.google.code.gson/gson/2.8.6/com.google.gson/module-summary.html

I am closing the issue for now. Feel free to re-open if the workaround doesn't work.

**Comment by Marcono1234** [comment]
Yes updating the URL manually after copying it works, thanks. However, it is slightly cumbersome which is why I wrote this feature request. It would be easier if they were separate versions so you could browse the 2.8.6 documentation and copy URLs and links without having to change the version in them first (which can be error-prone). Updating my initial feature request, maybe the "latest" dropdown label could include the version number as well to give more information, e.g. (formatted):
> - _latest_ (2.8.6)
> - 2.8.6
> - 2.8.5
> - ...

Since the version name is only in parentheses it should hopefully make the difference between "latest" and the currently latest version (e.g. 2.8.6) more clear.

Though thank you nonetheless even if you don't think this is worth implementing or would be confusing.
