### ISSUE TITLE
Support for bintray repositories whose packages haven't been published to jcenter. 

### ISSUE THREAD

**Issue by cmacfarl** [maxcellent/javadoc.io#55]
Support for being able to reference a bintray repository that is not linked to jcenter, but which contains publicly published packages would be nice.

e.g.  https://dl.bintray.com/[someuser]/maven/[somerepository]

Where [somerepository] is public, but for whatever reason is not on jcenter.

**Comment by maxcellent** [comment]
can you give me an example for me to test?

**Comment by cmacfarl** [comment]
Certainly.

https://dl.bintray.com/first-tech-challenge/ftcsdk/

That repository is not on jcenter, but there's javadoc in it's packages.  I think the idea would be that you allow people to add repos that are hosted on bintray itself to the list of repos that you scrape for packages.

**Comment by maxcellent** [comment]
hmmm this doesn't look like a repo with standard layout. How is this published? where is the `metadata.xml` file? where is `pom.xml`? javadoc.io relies on these files to organize artifacts

**Comment by cmacfarl** [comment]
The jars at the root of that repository shouldn't be there.  

However there are metadata and pom files associated with the packages themselves.

https://dl.bintray.com/first-tech-challenge/ftcsdk/org/firstinspires/ftc/Hardware/

Is that what you are looking for?

**Comment by maxcellent** [comment]
Thanks this is a good example. I think I understand the problem now. 

It looks like the root of the repo is: https://dl.bintray.com/first-tech-challenge/ftcsdk/, correct?

One more question, if I am a library user, how can I import the library from maven?

**Comment by cmacfarl** [comment]
Correct the root is https://dl.bintray.com/first-tech-challenge/ftcsdk/ but the actual packages live downstream in org/firstinspires/ftc.

Users use the packages by adding the following gradle to their builds.  

```
repositories {
    maven { url = "https://dl.bintray.com/first-tech-challenge/ftcsdk/" }
}

dependencies {
    implementation 'org.firstinspires.ftc:RobotCore:6.0.1'
    implementation 'org.firstinspires.ftc:Hardware:6.0.1'
    implementation 'org.firstinspires.ftc:FtcCommon:6.0.1'
}
```

**Comment by maxcellent** [comment]
I have manually added this repo. If there are more requests like this then will consider making this a self service.

https://javadoc.io/doc/org.firstinspires.ftc/RobotCore

**Comment by cmacfarl** [comment]
Thank you @maxcellent.  

Since bintray announced its shutdown, we've migrated all of our artifacts over to maven central.   Which means we can now use use javadoc.io in the manner it was intended to be used, however the RobotCore artifact appears to point to bintray, and hence won't update to our latest v6.2.1.   Is it possible to undo the manual addition so it can start picking up the artifacts in maven central?

Thank you.
