### ISSUE TITLE
package-list must always be provided as-is in text/plain

### ISSUE THREAD

**Issue by ffays** [maxcellent/javadoc.io#56]
It looks like that the "package-list" file at the root of the javadoc is sometimes embedded in a generated HTML file and sometimes provided as-is.

Could you please ensure that the file named "package-list" is always returned as-is in text/plain?

(Possibly could you check this is always the case for "element-info" file as well!?)

Two failing examples:
https://javadoc.io/doc/com.microsoft.ews-java-api/ews-java-api/latest/package-list
https://javadoc.io/doc/com.fasterxml.uuid/java-uuid-generator/latest/package-list

eg.

Failing : "text/html"  
```
curl -I https://javadoc.io/doc/com.fasterxml.uuid/java-uuid-generator/latest/package-list

HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
```

OK : "text/plain" (external example)

```
curl -I https://docs.oracle.com/javase/8/docs/api/package-list

HTTP/1.1 200 OK
Content-Type: text/plain
```

OK: "text/plain" 

```
curl -I https://www.javadoc.io/doc/com.google.guava/guava/27.1-jre/package-list

HTTP/1.1 200 OK
Content-Type: text/plain
```

**Comment by maxcellent** [comment]
When a version is specified, the response works. 

```
$ curl -I https://javadoc.io/doc/com.fasterxml.uuid/java-uuid-generator/4.0.1/package-list

HTTP/2 200
date: Sun, 18 Oct 2020 05:42:45 GMT
content-type: text/plain
```

What is your use case that content type matters?  As far as I can tell, the only place we need `package-list` is when we are generating with a javadoc reference. This file isn't really for human to read.

**Comment by maxcellent** [comment]
closing the ticket for now. Let me know if it's causing more issues.
