### ISSUE TITLE
libaums docs not working

### ISSUE THREAD

**Issue by magnusja** [maxcellent/javadoc.io#57]
Hey, 

any idea why this is not working?
https://www.javadoc.io/doc/me.jahnen/libaums/0.7.7/index.html

artifacts are here https://bintray.com/beta/#/magnusja/maven/libaums/0.7.7?tab=files

**Comment by maxcellent** [comment]
It looks like the `javadoc.jar` was uploaded twice and javadoc.io is only the first one.

I have reindexed the jar manually.
