### ISSUE TITLE
Requesting subpath of javadoc for the first time does not trigger download

### ISSUE THREAD

**Issue by nedtwigg** [maxcellent/javadoc.io#58]
First off, thanks so much for `javadoc.io`, love it.  I put links to it in our documentation, for example: `https://javadoc.io/static/com.diffplug.spotless/spotless-plugin-gradle/5.5.2/com/diffplug/gradle/spotless/FormatExtension.html#bumpThisNumberIfACustomStepChanges-int-`

The version number in the URL automatically updates when we publish a new version.  But if we follow the link, we get an

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
...
```

If we trim the subpath down to just `https://javadoc.io/static/com.diffplug.spotless/spotless-plugin-gradle/5.5.2`, then we get the `Javadoc is being downloaded. Normally this will be completed within 10 minutes.` message.  And after that, the subpath link works.  But the links are broken and stay broken until somebody thinks to manually trim off the subpath and request the naked root URL at least once.

**Comment by maxcellent** [comment]
hi, this should work. 

```
https://javadoc.io/doc/com.diffplug.spotless/spotless-plugin-gradle/5.5.2/com/diffplug/gradle/spotless/FormatExtension.html
```

Note: it's `javadoc.io/doc` instead of `javadoc.io/doc/static`
