### ISSUE TITLE
javadoc.io CDAP link to versions not working

### ISSUE THREAD

**Issue by liv123** [maxcellent/javadoc.io#60]
Where broken link appears: https://javadoc.io/doc/io.cdap.cdap

The first artifact on this page is "cdap". When I click on the latest version link (or any other cdap version link at this time), I get the following error:

> No JavaDoc is released for artifact io.cdap.cdap:cdap:6.2.2. Please try other versions.
> 
> Owner of the project? Troubleshoot following things:
> Retry this version. Sometimes it's just a matter of time to pick up new versions.
> Is the cdap-6.2.2-javadoc.jar actually distributed to either maven or bintray?
> Does the cdap-6.2.2-javadoc.jar file contains an index.html in the extracted root folder? (you can rename .jar to .zip to extract the file)
>  report to us if you tried everything but still doesn't work.

Solution: Can this link get hooked up properly or removed until it works? The info can still be accessed if I download the source and build my own copy of the JavaDocs.

**Comment by maxcellent** [comment]
As the page indicates, the library version 6.2.2 is released without a javadoc. 

Is it causing some issue on your end?

**Comment by maxcellent** [comment]
I am closing this issue for now. Let me know if it causes more issues
