### ISSUE TITLE
No JavaDoc is released for artifact com.prowidesoftware:pw-iso20022:SRU2020-9.1.3

### ISSUE THREAD

**Issue by zubri** [maxcellent/javadoc.io#61]
Hi,

Thanks for the javadoc.io site.

I'm getting the mentioned error when trying to load the javadoc for this package:
https://www.javadoc.io/doc/com.prowidesoftware/pw-iso20022/SRU2020-9.1.3/index.html

If I check the package the javadoc is properly submitted and listed at Maven Central.
https://repo1.maven.org/maven2/com/prowidesoftware/pw-iso20022/SRU2020-9.1.3/

PD: I'm one of the authors of the library

**Comment by maxcellent** [comment]
I unzipped jar file but there is no `index.html` under the jar file. 

It should just work once the jar file is generated with index.html under root folder

https://repo1.maven.org/maven2/com/prowidesoftware/pw-iso20022/SRU2020-9.1.3/pw-iso20022-SRU2020-9.1.3-javadoc.jar

**Comment by zubri** [comment]
OK thanks for your prompt response.
