### ISSUE TITLE
No Javadoc for io.cdap.cdap/cdap/6.2.3

### ISSUE THREAD

**Issue by dominic-messenger-hmrc** [maxcellent/javadoc.io#65]
Unable to source Javadoc for any io.cdap.cdap/cdap versions (6.1.3 and 6.2.3)
https://javadoc.io/doc/io.cdap.cdap/cdap/6.2.3/index.html
https://javadoc.io/doc/io.cdap.cdap/cdap/6.1.3/index.html

Can access Javadoc for API, clients and others

**Comment by maxcellent** [comment]
I don't see javadoc published with this library to maven central. 

https://repo1.maven.org/maven2/io/cdap/cdap/cdap/6.2.3/

Maybe you want to contact library owner if you expect one?
