### ISSUE TITLE
doc related to json schema validator was not found.

### ISSUE THREAD

**Issue by sjain55** [maxcellent/javadoc.io#66]
I was going through restAssured documentation (https://github.com/rest-assured/rest-assured/wiki/Usage#json-schema-validation) and found a link regarding json schema validation settings, which  seems to be broken.

link : http://static.javadoc.io/io.restassured/json-schema-validator/4.3.3/io/restassured/module/jsv/JsonSchemaValidatorSettings.html

**Comment by maxcellent** [comment]
I think there is a typo in the url. The following link works to me:

http://static.javadoc.io/io.rest-assured/json-schema-validator/4.3.3/io/restassured/module/jsv/JsonSchemaValidatorSettings.html
