### ISSUE TITLE
Javadoc.io out of service?

### ISSUE THREAD

**Issue by trustin** [maxcellent/javadoc.io#73]
It seems like the service has been down for several days. What's the plan for this service? Is it shutting down or just taking time to recover?

**Comment by maxcellent** [comment]
https://github.com/maxcellent/javadoc.io/issues/72

**Comment by trustin** [comment]
Ahh, thanks!

**Comment by maxcellent** [comment]
by the way, it could be netty related :) I will further investigate and let you know
