### ISSUE TITLE
Problem with  `/latest/package-list` and `/latest/element-list`

### ISSUE THREAD

**Issue by guillermocalvo** [maxcellent/javadoc.io#74]
I'm trying to [link some external classes referenced by my code](https://docs.oracle.com/en/java/javase/15/javadoc/javadoc-command.html#GUID-3894CFD5-88D5-407F-B603-3DCC826AE6EA) to their **latest version** on [javadoc.io](https://javadoc.io/).

I am using the `-link URL` option so Javadoc knows which external classes are documented on which javadoc.io pages:

```shell
javadoc options... \
  -link "https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-engine/latest/" \
  -link "https://javadoc.io/doc/org.assertj/assertj-core/latest/"
```

According to [Javadoc documentation](https://docs.oracle.com/en/java/javase/15/javadoc/javadoc-command.html#GUID-3894CFD5-88D5-407F-B603-3DCC826AE6EA), the `-link` option requires a file named `package-list` at the given URL. It is a simple text file that lists the names of packages documented at that location. It is automatically generated by the `javadoc` command and, as far as I know, it used to be `element-list` in older versions.

The problem is it doesn't work because the URL `https://javadoc.io/doc/GROUP_ID/ARTIFACT_ID/latest/package-list` does not return the actual text file but a web page that *embeds* the text contents. This prevents the Javadoc Tool from generating proper links:
- [junit-jupiter-engine/5.8.0-M1/package-list](https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-engine/5.8.0-M1/package-list) is `text/plain` but [junit-jupiter-engine/latest/package-list](https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-engine/latest/package-list) is `text/html`
- [assertj-core/3.19.0/element-list](https://javadoc.io/doc/org.assertj/assertj-core/3.19.0/element-list) is `text/plain` but [assertj-core/latest/element-list](https://javadoc.io/doc/org.assertj/assertj-core/latest/element-list) is `text/html`

I could use URLs with an actual version instead of "/latest" to make Javadoc work, but I'd prefer to generate links to the latest version of each library. Would it be possible to make `/latest/package-list` and `/latest/element-list` return a text/plain file instead of the HTML version?

**Comment by Masterzach32** [comment]
I'm experiencing the same issue using Dokka for generating docs in my code. The plugin cannot generate links since the package-list file, as well as the javadocs themselves are not listed directly.

**Comment by maxcellent** [comment]
added auto redirection:

eg, 
https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-engine/latest/package-list

will be redirected to
https://javadoc.io/doc/org.junit.jupiter/junit-jupiter-engine/5.8.0-M1/package-list
