### ISSUE TITLE
Javadoc not available for awsssmchaosrunner

### ISSUE THREAD

**Issue by ashish-k** [maxcellent/javadoc.io#75]
Javadoc not available for any version of awsssmchaosrunner

**Comment by maxcellent** [comment]
It looks like the index.html is not located at the root folder of the published jar file.  (the 3rd point of  https://www.javadoc.io/doc/software.amazon.awsssmchaosrunner/awsssmchaosrunner/latest/index.html)

Is there any special settings on the way to generate javadoc.jar file?

You can check by yourself: 

https://repo1.maven.org/maven2/software/amazon/awsssmchaosrunner/awsssmchaosrunner/1.3.0/awsssmchaosrunner-1.3.0-javadoc.jar

**Comment by maxcellent** [comment]
close the issue for now. feel free to re-open if you have new findings
