### ISSUE TITLE
Mockito Inline docs appear to be missing

### ISSUE THREAD

**Issue by jordanst3wart** [maxcellent/javadoc.io#76]
This might be a bug with Mockito inline library

https://javadoc.io/doc/org.mockito/mockito-inline/3.11.2/index.html

**Comment by maxcellent** [comment]
There is no index.html file in the disted jar file. So this is an expected behavior. Better to raise to mockito.

https://repo1.maven.org/maven2/org/mockito/mockito-inline/3.11.2/mockito-inline-3.11.2-javadoc.jar
