### ISSUE TITLE
Javadoc for camel-core 3.0.x to 3.11.0 not accessible

### ISSUE THREAD

**Issue by vishnuk15** [maxcellent/javadoc.io#77]
**_`No JavaDoc is released for artifact org.apache.camel:camel-core:3.11.0. Please try other versions.`_** 

https://www.javadoc.io/doc/org.apache.camel/camel-core/3.11.0/index.html
![CamelCoreJavaDoc](https://user-images.githubusercontent.com/42718589/126340789-7ba33c06-3837-4cdf-8e90-d120d6e7c065.jpg)

PS: Not sure if this is the right forum to address this issue. Apologies upfront.

**Comment by maxcellent** [comment]
There is no javadoc jar published for the version. So javadoc.io is behaving as expected.

eg, for 2.9.8. There is a camel-core-2.9.8-javadoc.jar  published under:
https://repo1.maven.org/maven2/org/apache/camel/camel-core/2.9.8/

but nothing for 3.11.0
https://repo1.maven.org/maven2/org/apache/camel/camel-core/3.11.0/
