### ISSUE TITLE
argparse4j javadoc access denied issue

### ISSUE THREAD

**Issue by martinda** [maxcellent/javadoc.io#78]
This link: https://javadoc.io/doc/net.sourceforge.argparse4j/argparse4j/latest/undefined/net/sourceforge/argparse4j/inf/Subparser.html

Gives:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>FD2770HXKSWDB5FV</RequestId>
<HostId>
HbY9idXjQeZOjBDS+Qj0Vtjr0jobPKA1pBQkL+cpHlETW3xdYJ/jQ8CJldXgaBEvk67XXhN/h6o=
</HostId>
</Error>
```

**Comment by maxcellent** [comment]
hi, I am able to access this page: https://javadoc.io/doc/net.sourceforge.argparse4j/argparse4j/latest/index.html

It looks like some style issue with the javadoc itself?
