### ISSUE TITLE
Allow -SNAPSHOT in the version

### ISSUE THREAD

**Issue by claudio-rosati** [maxcellent/javadoc.io#8]
Recognise -SNAPSHOT in the version to address the Sonatype Nexus (Snapshots) repository instead of Maven Central.

**Comment by maxcellent** [comment]
good point. A few changes need to be done:

1. set CDN cache to something like daily or hourly

1. provide ability to trigger a force refresh, otherwise from maven central point of view there is no new versions uploaded

**Comment by rnc** [comment]
Is this still on the todo list please?

**Comment by maxcellent** [comment]
Giving it another thought, sadly I don't think it's a good use case for javadoc.io. 

There are loads of optimizations (compression, long http expiry header, CDN policy) done with the assumption that the documents are immutable once released. Supporting SNAPSHOT version is just not quite fitting into the way it works.

I am closing the issue now.

**Comment by rnc** [comment]
Yeah makes sense, thanks for letting me know!
