### ISSUE TITLE
Javadoc for 4.x 

### ISSUE THREAD

**Issue by mahebaby** [maxcellent/javadoc.io#82]
https://javadoc.io/doc/com.squareup.okhttp3/okhttp/4.0.0/index.html
Unable to find Javadocs for 4.x and above versions. Latest available is 3.14.9. 
Kindly share the updated doc link.

**Comment by maxcellent** [comment]
This is because the published jar is empty. So it's a question for library owner why they stop publishing javadoc.

https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/4.0.0/okhttp-4.0.0-javadoc.jar
