### ISSUE TITLE
Links from within the docs open incorrectly on https://www.javadoc.io/doc/...

### ISSUE THREAD

**Issue by p-bakker** [maxcellent/javadoc.io#83]
A link to a class (in the packageFrame iframe) has as target the value 'classFrame'

However, there are 2 iframes with that name: the main iframe in which the static Javadoc html is loaded and one within the static javadoc html.

When for example a link to a class is clicked, instead of updating the displayed class in the nested iframe with the name 'classFrame', instead it is opened in the main iframe with the same name.

You can see the difference when comparing what happens when clicking a Class link on https://www.javadoc.io/doc/... vs clikcing the same link on https://www.javadoc.io/static/...

In Firefox, if I change the name of the main iframe on https://www.javadoc.io/doc/... the problem is solved and it starts behaving similarly as https://www.javadoc.io/static/... 

In Google Chrome changing the name attribute doesn't make it behave differently, you'd have to change the name property of the 'window' object of the page inside the main iframe (window.name = '__classFrame')

**Comment by p-bakker** [comment]
would love to create a small PR for this, but there's no sourcecode here...

**Comment by maxcellent** [comment]
hi, would you please explain what the problem is? How do you mean by `change the name of the main iframe`? 

The only difference between  https://www.javadoc.io/doc/... vs https://www.javadoc.io/static/... is the /doc/ one has a top navigation.

**Comment by p-bakker** [comment]
The page on /docs (with the added navigation) runs the/static page in an iframe.

That iframe has a name attribute with the value 'classFrame'

However, the /static page also uses frames and one of those also has the name 'classFrame'

As a result, when you view the docs via /doc, there are 2 frames in the markup of the page with the same name. And sure to that, when you click a anchor/link that has 'classFrame' as it's target, the browser sees 2 potential targets and picks the first

So, on the /doc site, if you click on a link in the lower left frame (that lists all the classes), you lose the frameset and instead are shown only the class

**Comment by p-bakker** [comment]
See these screenshots for probably a clearer explanations:
![image](https://user-images.githubusercontent.com/4981149/145827507-d9d4d527-0f2d-4f0f-a685-27775ad19654.png)
![image](https://user-images.githubusercontent.com/4981149/145827665-7b2a661c-36a7-4d6b-9db5-647214f216a2.png)

If you change the name of the iframe to something like `staticDocs`, the problem is solved

**Comment by maxcellent** [comment]
This element name is actually added deliberately because of another issue: https://github.com/maxcellent/javadoc.io/issues/27

Will think about alternatives

**Comment by p-bakker** [comment]
Any luck coming up with an alternative approach?

**Comment by maxcellent** [comment]
this should be resolved now.
