### ISSUE TITLE
How to request inclusion in Javadoc.io

### ISSUE THREAD

**Issue by davidjgonzalez** [maxcellent/javadoc.io#86]
I have a Maven artifact [1] (on Central Maven) whose JavaDocs i'd like to have surfaced on Javadoc.io - how do i go about requesting this?

Thanks

[1] https://search.maven.org/artifact/com.adobe.aem.commons/assetshare.core/2.2.0/jar

**Comment by maxcellent** [comment]
hi, you have probably figured already. There is no need to request. The first time you visit this page the website will index the javadoc.

https://javadoc.io/doc/com.adobe.aem.commons/assetshare.core/2.2.0
