### ISSUE TITLE
Remove default border around iframe

### ISSUE THREAD

**Issue by Marcono1234** [maxcellent/javadoc.io#87]
It appears that the `<iframe>` containing the actual documentation has a default border (at least for Firefox 98.0.1 (64-Bit)). This is a bit annoying because when you move your mouse all the way to the right of your screen and then try to drag the scroll bar, it does not work because you actually have the mouse above the tiny border around the `<iframe>` instead of the scroll bar.

Would it be possible to remove the default border?

Reproduction steps:
1. Open for example https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/2.13.1/com/fasterxml/jackson/annotation/JsonTypeInfo.html
2. At the height of the vertical scroll bar handle, move your mouse all the way to the right of your screen
3. Press down the left mouse button and try to drag the scroll bar
:x: Nothing happens

**Comment by maxcellent** [comment]
![image](https://user-images.githubusercontent.com/2378229/174428792-2f7a3e82-caed-4fd9-b296-a28dee7046b8.png)

hi, I am not sure if I am able to reproduce the issue. Would you be able to provide more details? Like do you see the same as what I see from screenshot?

**Comment by Marcono1234** [comment]
The border is (I assume) only 1 pixel wide so this is not a visual problem, but a behavioral problem.

I am using Windows 10, and am experiencing this issue with both Firefox and Edge. Hopefully these reproduction steps make it a bit clearer:
1. Make the browser window fill the complete screen; you can also use fullscreen mode (in Edge <kbd>F11</kbd>)
2. Open https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/2.13.1/com/fasterxml/jackson/annotation/JsonTypeInfo.html or any other documentation which has a vertical scroll bar by default
3. Move your mouse completely to the right of the screen, so that it is (at least on Windows) nearly completely outside the visible area
4. Try to scroll with your mouse wheel or by pressing down your left mouse button and trying to drag the scrollbar

The following video shows to demonstrate this issue in Edge:

https://user-images.githubusercontent.com/11685886/174455610-d68f3aeb-c103-429b-850d-719d8d2a8c19.mp4

It shows the following:
1. When the mouse is above the scrollbar the scrollbar turns dark gray
2. When moving the mouse completely to the right of the screen the mouse is not above the scrollbar anymore (the scrollbar color changes to light gray again); dragging the scrollbar or using the mouse wheel is not possible
3. After manually setting `border: 0px` for the `iframe` the mouse is on top of the scrollbar and the scrollbar can be used, even when completely at the edge of the screen, as desired

**Comment by maxcellent** [comment]
Ah I see what you mean. I am on dual monitors and my browser is usually on the left so never had this issue. Added this style as suggested.
