### ISSUE TITLE
Faux Pas 0.6.0 not available

### ISSUE THREAD

**Issue by garretwilson** [maxcellent/javadoc.io#9]
Maven Central says Faux Pas 0.6.0 is available since January 2018:

https://search.maven.org/#artifactdetails%7Corg.zalando%7Cfaux-pas%7C0.6.0%7Cjar

But this gives me an access denied error:

https://static.javadoc.io/org.zalando/faux-pas/0.6.0/org/zalando/fauxpas/FauxPas.html

But version 0.5.0 works:

https://static.javadoc.io/org.zalando/faux-pas/0.5.0/org/zalando/fauxpas/FauxPas.html

**Comment by cretz** [comment]
@garretwilson - I had a similar problem, so I went specifically to http://javadoc.io/doc/org.zalando/faux-pas/0.6.0 which forced the download and now your link works.

**Comment by garretwilson** [comment]
Thanks for the good news. This still seems to indicate some sort of bug, though; I hope whatever caused it gets fixed.

**Comment by maxcellent** [comment]
Thanks for the workaround. Will investigate and make it more automated.
