### ISSUE TITLE
Javadoc 522 Timed out

### ISSUE THREAD

**Issue by momlesstomato** [maxcellent/javadoc.io#96]
Hello. I have noticed that javadoc.io is throwing 522 error. I would like to know if it is normal of the server or it is a bug of mine.

`Error fetching URL: https://javadoc.io/doc/org.yaml/snakeyaml/1.30/ (java.io.IOException: Server returned HTTP response code: 522 for URL: https://javadoc.io/doc/org.yaml/snakeyaml/1.30/package-list)`

**Comment by maxcellent** [comment]
There was an out of memory error issue. Now fixed.
