### ISSUE TITLE
Javadoc search navigation is broken

### ISSUE THREAD

**Issue by joel-costigliola** [maxcellent/javadoc.io#97]
Thanks for your excellent javadoc.io, I have noticed a bug/regression related to navigating after a search (on top right text field).

https://www.javadoc.io/doc/org.assertj/assertj-core/latest/index.html search works except for navigating to the selected element.

I have generated the javadoc locally and the navigation works so I assume something is blocking the navigation in javadoc.io

**Comment by maxcellent** [comment]
This issue is initially reported by you and fixed: https://github.com/maxcellent/javadoc.io/issues/27 

However, because of the recent issue: https://github.com/maxcellent/javadoc.io/issues/83

We have to reverse changes on #27 . Instead, we need to run a migration task to fix all `search.js` generated from OpenJDK. The job is already running but considering the total number of files is massive. This will take about a week or two. I will keep this issue open until the whole migration is finished.

**Comment by maxcellent** [comment]
It looks like this link you mentioned is already fixed.

**Comment by joel-costigliola** [comment]
thanks for the info, the javadoc is not yet working (I just tried) but I'll check in a couple days.

**Comment by maxcellent** [comment]
Does this work to you? https://www.javadoc.io/doc/org.assertj/assertj-core/3.23.0/org/assertj/core/api/exception/PathsException.html

**Comment by joel-costigliola** [comment]
yes it does

**Comment by maxcellent** [comment]
how about shift + F5 on this page? https://www.javadoc.io/doc/org.assertj/assertj-core/latest/index.html

**Comment by joel-costigliola** [comment]
nope. I was trying on ffox

just tried on chrome, it does not work either

**Comment by scordio** [comment]
It seems to be a local issue, for me it works fine in incognito mode with both Firefox and Chrome, but wasn't working on Firefox without incognito mode.

Clearing cookies for javadoc.io fixed it for me.

**Comment by joel-costigliola** [comment]
it works for me now after clearing the cookies, I'm closing the issue, thanks all!

**Comment by scordio** [comment]
Hi @maxcellent, more users are reporting the same issue in assertj/assertj-core#2684 and it seems that clearing cookies are not really the solution.

Just inspecting the page source, I noticed the locally generated Javadoc uses:

```
<script type="text/javascript" src="[script-dir/jquery-3.5.1.min.js](view-source:http://localhost:63342/assertj-core/target/site/apidocs/script-dir/jquery-3.5.1.min.js)"></script>
```

but on javadoc.io I see:

```
<script src="[https://code.jquery.com/jquery-3.3.1.min.js](view-source:https://code.jquery.com/jquery-3.3.1.min.js)" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
```

and https://github.com/assertj/assertj-core/issues/2684#issuecomment-1165589305 mentions an issue with the search, related to outdated JS files:

> I suspect the problem may be in your browser: you can have outdated JS files that work, I load fresh JS files and they are broken.

I'm no frontend expert so I'm already out of my comfort zone 😅 do you see a way to resolve this issue?

**Comment by maxcellent** [comment]
hi @scordio, this is not related. One is used for parent iframe and one is used for the child. 

So I think this is because the migration is still in progress, currently about 20% is completed and will need another week or two. 

During this period, some versions might be working and some might. Would that be possible to ask your users to use the javadoc for latest version for now?

**Comment by scordio** [comment]
As far as I understood, we and our users are having issues with the latest version only.

**Comment by maxcellent** [comment]
so this is likely a caching issue from CDN. I have purged everything. Now if you do Ctrl + refresh it should work now.

I have test both Chrome and Firefox against latest version.

**Comment by joel-costigliola** [comment]
Users report it works now so I'm closing the issue.

**Comment by Marcono1234** [comment]
> So I think this is because the migration is still in progress, currently about 20% is completed and will need another week or two.

@maxcellent, could you please comment here again once the migration finished for all projects (or reopen the issue and close it again once the migration is done)?
It appears it is not working for all projects yet, for example it does not seem to be working for 
https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/module-summary.html

**Comment by maxcellent** [comment]
@Marcono1234 sure will do. 

I have manually fixed this page for now: https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/ExclusionStrategy.html

**Comment by maxcellent** [comment]
It's completed. Please re-open if you see this issue again even after refresh
