### ISSUE TITLE
Broken links generated by the search feature for the `latest` version

### ISSUE THREAD

**Issue by marcwrobel** [maxcellent/javadoc.io#99]
It seems the links generated by the search feature are broken for the `latest` version.

Step to reproduce :
1. Go to https://javadoc.io/doc/fr.marcwrobel/jbanking/
2. Search for `Iban`
3. Click on the _type_ `fr.marcwrobel.jbanking.iban.Iban`
4. You are redirected to https://javadoc.io/doc/fr.marcwrobel/jbanking/latest/undefined/fr/marcwrobel/jbanking/iban/Iban.html.
5. You can see the following error.

```
<Error>
<Code>AccessDenied</Code>
<BucketName>prod-web-06</BucketName>
<RequestId>tx0000000000000ee338b8d-0062c35e0e-3199e787-nyc3c</RequestId>
<HostId>3199e787-nyc3c-nyc3-zg03</HostId>
</Error>
```
The correct link is https://javadoc.io/doc/fr.marcwrobel/jbanking/latest/fr/marcwrobel/jbanking/iban/Iban.html, not https://javadoc.io/doc/fr.marcwrobel/jbanking/latest/undefined/fr/marcwrobel/jbanking/iban/Iban.html : `undefined` is concatenated after `latest` in the broken link.

The issue affects only the `latest` version : when reproducing the same steps for an older version (for example https://javadoc.io/doc/fr.marcwrobel/jbanking/3.1.0/) everything works as expected.

**Comment by maxcellent** [comment]
This is a known JDK issue: https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url

You can reproduce by generating javadoc on your local machine directly.

**Comment by marcwrobel** [comment]
Thanks @maxcellent, and sorry for the bother: I should have searched in the closed issues before opening this one.
